#!/bin/sh

set -xe

TAG="`date +%s`_`git rev-parse --short HEAD`"
IMAGE_REGISTRY="rg.nl-ams.scw.cloud/hyperfocus"
CONFIG_DIR="/tmp/hyperfocus-config-$TAG"

echo "Using tag: $TAG"

FRONTEND_IMAGE="${IMAGE_REGISTRY}/hyperfocus-frontend:${TAG}"
BACKEND_IMAGE="${IMAGE_REGISTRY}/hyperfocus-backend:${TAG}"

docker build --platform=linux/amd64 . -f ./frontend/Dockerfile -t "${FRONTEND_IMAGE}"
docker build --platform=linux/amd64 . -f ./backend/Dockerfile -t "${BACKEND_IMAGE}"

docker push "${FRONTEND_IMAGE}"
docker push "${BACKEND_IMAGE}"

trap "rm -rf '$CONFIG_DIR'" EXIT
(
    mkdir "$CONFIG_DIR"
    cd "$CONFIG_DIR"
    ls
    git clone git@github.com-adrianhelvik:adrianhelvik/hyperfocus-config.git
    cd hyperfocus-config
    (cd scripts && bun install)
    bun scripts/set-image-tag.ts hyperfocus-backend "$TAG"
    bun scripts/set-image-tag.ts hyperfocus-frontend "$TAG"
    git add -A
    git commit -m "Auto-deploy: $TAG"
    git push
)
