version: '3'

services:
  frontend:
    image: subtask-frontend
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 9341:9341
    environment:
      NODE_ENV: 'development'
      API_URL: http://backend:1234
      REWRITE: 'true'

  backend:
    image: subtask-backend
    restart: always
    ports:
      - 1234:1234
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      NODE_ENV: 'development'
      UPLOADS_BASE_URL: "http://localhost:1234"
      PGPASSWORD: 'SomeRandomDevelopmentPasswordAAGDDNDGEA'
      PGDATABASE: 'subtask'
      PGUSER: 'subtask'
      PGHOST: 'postgres'
      PGPORT: '5432'
      TERM: 'xterm'
    command: sh -c 'yarn knex migrate:latest && yarn start --colors'
    volumes:
      - ./backend/src:/backend/src

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: subtask
      POSTGRES_USER: subtask
      POSTGRES_PASSWORD: SomeRandomDevelopmentPasswordAAGDDNDGEA
    restart: always
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
