services:
  frontend:
    image: subtask-frontend
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: install
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 9341:9341
    environment:
      PRELOAD_FILES: 'true'
      NODE_ENV: 'development'
      API_URL: 'http://backend:1234'
      REWRITE: 'true'
      PORT: '9341'

  backend:
    image: subtask-backend
    restart: always
    ports:
      - 1234:1234
    depends_on:
      - keydb
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    environment:
      NODE_ENV: 'development'
      #SOCKET_IO_KEYDB: "redis://keydb"
      UPLOADS_BASE_URL: "http://localhost:1234"
      PGPASSWORD: 'SomeRandomDevelopmentPasswordAAGDDNDGEA'
      PGDATABASE: 'subtask'
      PGUSER: 'subtask'
      PGHOST: 'postgres'
      PGPORT: '5432'
      TERM: 'xterm'
    volumes:
      - ./backend/src:/backend/src

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: subtask
      POSTGRES_USER: subtask
      POSTGRES_PASSWORD: SomeRandomDevelopmentPasswordAAGDDNDGEA
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:alpine
