#!/bin/bash

RETRIES=20

echo "PGPORT: $PGPORT"
echo "PGHOST: $PGHOST"
echo "PGUSER: $PGUSER"
echo "PGPASSWORD: $PGPASSWORD"
echo "PGDATABASE: $PGDATABASE"

until psql -c "select 1" || [ $RETRIES -eq 0 ]; do
  echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
  sleep 1
done
